//#include <Windows.h>

//#define DEBUG
#define GRAVITY					1
#define JUMP_STRENGTH			3
#define JUMP_TIME_LIMIT			3
#define MAP_MOVESPEED			1
#define MARIO_MOVE_SPEED		5

#define NORMAL_SCREEN_WIDTH		400
#define NORMAL_SCREEN_HEIGHT	250
#define FULL_SCREEN_WIDTH		(int)((DOUBLE)(GetSystemMetrics(SM_CXSCREEN) / (DOUBLE)NORMAL_SCREEN_WIDTH) >= ((DOUBLE)GetSystemMetrics(SM_CYSCREEN) / (DOUBLE)NORMAL_SCREEN_HEIGHT) ? (NORMAL_SCREEN_WIDTH * ((DOUBLE)GetSystemMetrics(SM_CYSCREEN) / (DOUBLE)NORMAL_SCREEN_HEIGHT)) : (GetSystemMetrics(SM_CXSCREEN)))
#define FULL_SCREEN_HEIGHT		(int)((DOUBLE)(GetSystemMetrics(SM_CXSCREEN) / (DOUBLE)NORMAL_SCREEN_WIDTH) >= ((DOUBLE)GetSystemMetrics(SM_CYSCREEN) / (DOUBLE)NORMAL_SCREEN_HEIGHT) ? (GetSystemMetrics(SM_CYSCREEN)) : (NORMAL_SCREEN_HEIGHT * ((DOUBLE)GetSystemMetrics(SM_CXSCREEN) / (DOUBLE)NORMAL_SCREEN_WIDTH)))
#define SCREEN_WIDTH			GetSystemMetrics(SM_CXSCREEN)
#define SCREEN_HEIGHT			GetSystemMetrics(SM_CYSCREEN)
